### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by leovarmak** [mariorodeghiero/git-commands#3]
Hey,

Please release binaries so noobs like me don't have to go through all the steps

Regards,
Karthik.

**Comment by mariorodeghiero** [comment]
Good idea @leovarmak, I'll compile and generate the binaries and make it available for download in GitPages.

But you generated the binary and it worked?

Thank you!

**Comment by leovarmak** [comment]
I haven't. I was too lazy 🙈 
Like usually there are binaries provided in the releases section.

**Comment by mariorodeghiero** [comment]
@leovarmak I created the executables and made it available for download in Git Pages here [mariorodeghiero.com/git-cheatsheet](https://mariorodeghiero.com/git-cheatsheet/)

Thank you for the idea.
